# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_active',
            new_name='is_done',
        ),
    ]
